import React, { useState, useRef } from 'react';
import { AnalysisResult } from '../types';
import { CheckCircle, XCircle, AlertTriangle, HelpCircle, Share2, Shield, Eye, ThumbsDown, Activity, ChevronRight, Lock, Volume2, FileDown, Mic, FileText, Link as LinkIcon, ScanFace, Binary } from 'lucide-react';
import { jsPDF } from 'jspdf';
import { generateAudioReport } from '../services/geminiService';

interface ResultsViewProps {
  result: AnalysisResult;
  onReset: () => void;
}

// Helper to decode raw PCM audio data
function decode(base64: string) {
  const binaryString = atob(base64);
  const len = binaryString.length;
  const bytes = new Uint8Array(len);
  for (let i = 0; i < len; i++) {
    bytes[i] = binaryString.charCodeAt(i);
  }
  return bytes;
}

export const ResultsView: React.FC<ResultsViewProps> = ({ result, onReset }) => {
  const [isPlaying, setIsPlaying] = useState(false);
  const [isGeneratingPdf, setIsGeneratingPdf] = useState(false);
  const [selectedLanguage, setSelectedLanguage] = useState('English');
  const [selectedGender, setSelectedGender] = useState<'male' | 'female'>('female');
  
  const getStatusColor = (status: string) => {
    switch (status) {
      case 'Real': return 'text-green-400 border-green-500/50 bg-green-500/5 shadow-[0_0_30px_rgba(34,197,94,0.1)]';
      case 'Fake': return 'text-red-400 border-red-500/50 bg-red-500/5 shadow-[0_0_30px_rgba(239,68,68,0.1)]';
      case 'Misleading': return 'text-orange-400 border-orange-500/50 bg-orange-500/5 shadow-[0_0_30px_rgba(249,115,22,0.1)]';
      case 'Satire': return 'text-purple-400 border-purple-500/50 bg-purple-500/5 shadow-[0_0_30px_rgba(168,85,247,0.1)]';
      default: return 'text-slate-400 border-slate-500/50 bg-slate-500/5';
    }
  };

  const getStatusIcon = (status: string) => {
    switch (status) {
      case 'Real': return <CheckCircle className="w-16 h-16" />;
      case 'Fake': return <XCircle className="w-16 h-16" />;
      case 'Misleading': return <AlertTriangle className="w-16 h-16" />;
      case 'Satire': return <Eye className="w-16 h-16" />;
      default: return <HelpCircle className="w-16 h-16" />;
    }
  };

  const handleDownloadPDF = () => {
    setIsGeneratingPdf(true);
    const doc = new jsPDF();
    
    // Header
    doc.setFillColor(10, 10, 10);
    doc.rect(0, 0, 210, 20, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(16);
    doc.text("TruthLens Intelligence Report", 10, 13);
    
    // Status
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(22);
    doc.text(`VERDICT: ${result.classification.toUpperCase()}`, 10, 40);
    
    doc.setFontSize(12);
    doc.text(`Confidence: ${result.confidence}% | Virality Risk: ${result.viralityScore}/100`, 10, 50);
    
    // Summary
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.text("Executive Summary", 10, 65);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(11);
    
    const splitSummary = doc.splitTextToSize(result.summary, 180);
    doc.text(splitSummary, 10, 75);
    
    let yPos = 75 + (splitSummary.length * 7) + 10;
    
    // Reasoning
    doc.setFont("helvetica", "bold");
    doc.setFontSize(14);
    doc.text("Key Reasoning", 10, yPos);
    yPos += 10;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(11);
    
    result.reasoning.forEach(point => {
        const splitPoint = doc.splitTextToSize(`• ${point}`, 180);
        doc.text(splitPoint, 10, yPos);
        yPos += (splitPoint.length * 7);
    });

    // Fact Checks
    if (result.factChecks.length > 0) {
        yPos += 10;
        doc.setFont("helvetica", "bold");
        doc.setFontSize(14);
        doc.text("Fact Checks", 10, yPos);
        yPos += 10;
        doc.setFont("helvetica", "normal");
        doc.setFontSize(10);
        
        result.factChecks.forEach(check => {
            const line = `[${check.verdict}] ${check.claim} (Source: ${check.source})`;
            const splitLine = doc.splitTextToSize(line, 180);
            doc.text(splitLine, 10, yPos);
            yPos += (splitLine.length * 6) + 2;
        });
    }

    // Footer
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text(`Generated by TruthLens AI • ${new Date().toLocaleString()}`, 10, 280);
    
    doc.save(`truthlens-report-${Date.now()}.pdf`);
    setIsGeneratingPdf(false);
  };

  const handlePlayAudio = async () => {
    if (isPlaying) return;
    setIsPlaying(true);
    
    try {
        const audioData = await generateAudioReport(result.summary, result.classification, selectedLanguage, selectedGender);
        
        if (audioData) {
            const audioContext = new (window.AudioContext || (window as any).webkitAudioContext)({sampleRate: 24000});
            const audioBuffer = await audioContext.decodeAudioData(decode(audioData).buffer);
            
            const source = audioContext.createBufferSource();
            source.buffer = audioBuffer;
            source.connect(audioContext.destination);
            source.start(0);
            
            source.onended = () => setIsPlaying(false);
        } else {
            setIsPlaying(false);
        }
    } catch (e) {
        console.error("Failed to play audio", e);
        alert("Failed to generate voice report.");
        setIsPlaying(false);
    }
  };

  return (
    <div className="max-w-5xl mx-auto animate-fade-in pb-12">
      <div className="flex justify-between items-center mb-6">
        <button onClick={onReset} className="text-slate-400 hover:text-white transition-colors flex items-center group">
            <div className="bg-white/5 p-2 rounded-lg mr-2 group-hover:bg-white/10 transition-colors">
                <ChevronRight className="w-4 h-4 rotate-180" />
            </div>
            Back to Engine
        </button>

        <div className="flex items-center space-x-2">
            {/* Voice Controls */}
            <div className="glass-panel px-3 py-1.5 rounded-lg flex items-center space-x-2 border-white/5 bg-black/50">
                <select 
                    value={selectedLanguage}
                    onChange={(e) => setSelectedLanguage(e.target.value)}
                    className="bg-transparent text-xs text-white outline-none border-none cursor-pointer"
                >
                    <option value="English">English</option>
                    <option value="Hindi">Hindi</option>
                    <option value="Spanish">Spanish</option>
                    <option value="French">French</option>
                    <option value="German">German</option>
                </select>
                <div className="h-4 w-px bg-white/20"></div>
                <button 
                    onClick={() => setSelectedGender('male')}
                    className={`text-xs px-2 py-0.5 rounded ${selectedGender === 'male' ? 'bg-blue-500/20 text-blue-400' : 'text-slate-500'}`}
                >
                    Male
                </button>
                <button 
                    onClick={() => setSelectedGender('female')}
                    className={`text-xs px-2 py-0.5 rounded ${selectedGender === 'female' ? 'bg-pink-500/20 text-pink-400' : 'text-slate-500'}`}
                >
                    Female
                </button>
            </div>

            <button 
                onClick={handlePlayAudio}
                disabled={isPlaying}
                className="flex items-center space-x-2 px-4 py-2 rounded-lg bg-indigo-500/10 text-indigo-400 hover:bg-indigo-500/20 border border-indigo-500/20 transition-all disabled:opacity-50"
            >
                {isPlaying ? (
                    <div className="flex space-x-1 items-center">
                        <span className="w-1 h-3 bg-indigo-400 animate-pulse"></span>
                        <span className="w-1 h-2 bg-indigo-400 animate-pulse delay-75"></span>
                        <span className="w-1 h-3 bg-indigo-400 animate-pulse delay-150"></span>
                    </div>
                ) : (
                    <Volume2 className="w-4 h-4" />
                )}
                <span className="text-sm font-bold">Listen</span>
            </button>

            <button 
                onClick={handleDownloadPDF}
                disabled={isGeneratingPdf}
                className="flex items-center space-x-2 px-4 py-2 rounded-lg bg-white/5 text-slate-300 hover:bg-white/10 border border-white/10 transition-all"
            >
                <FileDown className="w-4 h-4" />
                <span className="text-sm font-bold">{isGeneratingPdf ? 'Generating...' : 'Report'}</span>
            </button>
        </div>
      </div>

      {/* Main Verdict Card */}
      <div className={`glass-panel rounded-3xl p-10 mb-8 text-center border ${getStatusColor(result.classification).split(' ')[1]} ${getStatusColor(result.classification).split(' ')[3]} relative overflow-hidden`}>
        {/* Scanning grid effect */}
        <div className="absolute inset-0 bg-[linear-gradient(rgba(255,255,255,0.03)_1px,transparent_1px),linear-gradient(90deg,rgba(255,255,255,0.03)_1px,transparent_1px)] bg-[size:40px_40px] opacity-20 pointer-events-none"></div>
        <div className="absolute top-0 left-0 w-full h-32 bg-gradient-to-b from-white/5 to-transparent pointer-events-none"></div>
        
        <div className="relative z-10 flex flex-col items-center justify-center">
            <div className="mb-6 relative">
                 <div className={`absolute inset-0 blur-3xl opacity-20 ${result.classification === 'Real' ? 'bg-green-500' : 'bg-red-500'}`}></div>
                 {getStatusIcon(result.classification)}
            </div>
          
            <h2 className={`text-6xl font-black tracking-tighter mb-4 ${getStatusColor(result.classification).split(' ')[0]}`}>{result.classification.toUpperCase()}</h2>
            <p className="text-xl text-slate-300 max-w-3xl mx-auto leading-relaxed">{result.summary}</p>

            <div className="grid grid-cols-1 md:grid-cols-3 gap-8 mt-10 w-full max-w-3xl">
                <div className="bg-black/40 border border-white/5 p-4 rounded-2xl flex flex-col items-center">
                    <span className="text-3xl font-bold text-white mb-1">{result.confidence}%</span>
                    <span className="text-xs text-slate-500 uppercase tracking-widest font-semibold">AI Confidence</span>
                </div>
                <div className="bg-black/40 border border-white/5 p-4 rounded-2xl flex flex-col items-center">
                    <span className={`text-3xl font-bold mb-1 ${result.viralityScore > 70 ? 'text-red-400' : 'text-slate-200'}`}>
                        {result.viralityScore}<span className="text-sm text-slate-500">/100</span>
                    </span>
                    <span className="text-xs text-slate-500 uppercase tracking-widest font-semibold">Virality Index</span>
                </div>
                <div className="bg-black/40 border border-white/5 p-4 rounded-2xl flex flex-col items-center">
                    <span className={`text-3xl font-bold mb-1 ${result.isAiGenerated ? 'text-purple-400' : 'text-blue-400'}`}>
                        {result.isAiGenerated ? 'HIGH' : 'LOW'}
                    </span>
                    <span className="text-xs text-slate-500 uppercase tracking-widest font-semibold">Synthetic Origin</span>
                </div>
            </div>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        
        {/* Left Col: Reasoning & Evidence */}
        <div className="md:col-span-2 space-y-6">
          
          {/* Deepfake Analysis Module */}
          {result.isAiGenerated && (
             <div className="glass-panel p-1 rounded-3xl border border-purple-500/30 overflow-hidden relative">
                 <div className="absolute inset-0 bg-purple-900/10 pointer-events-none"></div>
                 <div className="p-6 bg-black/40">
                     <div className="flex items-center space-x-3 mb-4">
                        <ScanFace className="w-6 h-6 text-purple-400" />
                        <h3 className="text-xl font-bold text-white">Deepfake Forensics Report</h3>
                     </div>
                     <p className="text-sm text-purple-200 mb-6">
                        <Binary className="w-4 h-4 inline mr-1" />
                        Visual artifacts consistent with generative models detected.
                     </p>
                     
                     <div className="grid grid-cols-2 gap-4">
                        <div className="bg-purple-500/10 border border-purple-500/20 p-4 rounded-xl">
                            <span className="text-xs font-bold text-purple-400 uppercase block mb-1">Pattern Anomaly</span>
                            <span className="text-white font-mono text-sm">Texture Smoothing (Face)</span>
                            <div className="w-full h-1 bg-purple-900 rounded-full mt-2">
                                <div className="w-[85%] h-full bg-purple-500 rounded-full"></div>
                            </div>
                        </div>
                        <div className="bg-purple-500/10 border border-purple-500/20 p-4 rounded-xl">
                            <span className="text-xs font-bold text-purple-400 uppercase block mb-1">Lighting Consistency</span>
                            <span className="text-white font-mono text-sm">Shadow Mismatch</span>
                            <div className="w-full h-1 bg-purple-900 rounded-full mt-2">
                                <div className="w-[60%] h-full bg-purple-500 rounded-full"></div>
                            </div>
                        </div>
                     </div>
                 </div>
             </div>
          )}

          {/* Explainable AI Logic Chain */}
          <div className="glass-panel p-8 rounded-3xl border-white/5">
            <h3 className="text-xl font-bold text-white mb-6 flex items-center">
              <Shield className="w-5 h-5 mr-3 text-primary-400" />
              Reasoning Logic Chain
            </h3>
            <div className="relative border-l-2 border-slate-800 ml-4 space-y-8 py-2">
              {result.reasoning.map((reason, idx) => (
                <div key={idx} className="relative pl-8">
                   <div className="absolute -left-[9px] top-0 w-4 h-4 rounded-full bg-black border-2 border-primary-500 flex items-center justify-center">
                       <div className="w-1.5 h-1.5 rounded-full bg-primary-500"></div>
                   </div>
                   <h4 className="text-sm font-bold text-primary-400 uppercase mb-1">Logic Step {idx + 1}</h4>
                   <p className="text-slate-300 leading-relaxed text-sm">{reason}</p>
                </div>
              ))}
            </div>
          </div>

          {/* Evidence Board */}
          {result.factChecks.length > 0 && (
            <div className="glass-panel p-8 rounded-3xl border-white/5">
              <h3 className="text-xl font-bold text-white mb-6 flex items-center">
                <Activity className="w-5 h-5 mr-3 text-green-400" />
                Evidence & Verification
              </h3>
              <div className="grid grid-cols-1 gap-4">
                {result.factChecks.map((check, idx) => (
                  <div key={idx} className="border border-white/5 bg-black/30 p-5 rounded-xl hover:bg-white/5 transition-colors group">
                    <div className="flex justify-between items-start mb-3">
                        <span className="flex items-center space-x-2 text-xs font-bold text-slate-500 uppercase">
                            <FileText className="w-3 h-3" />
                            <span>Claim Analysis</span>
                        </span>
                        <span className={`text-xs font-bold px-2 py-1 rounded border ${
                             check.verdict.toLowerCase().includes('true') || check.verdict.toLowerCase().includes('supported') 
                             ? 'bg-green-500/10 text-green-400 border-green-500/20' 
                             : 'bg-red-500/10 text-red-400 border-red-500/20'
                        }`}>
                            {check.verdict}
                        </span>
                    </div>
                    <p className="text-white font-medium mb-4">"{check.claim}"</p>
                    
                    <div className="flex items-center pt-3 border-t border-white/5">
                       <LinkIcon className="w-3 h-3 text-primary-400 mr-2" />
                       <span className="text-xs text-primary-400 font-mono">Source: {check.source}</span>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          )}
        </div>

        {/* Right Col: Emotional & Actions */}
        <div className="space-y-6">
          <div className="glass-panel p-8 rounded-3xl border-white/5">
            <h3 className="text-xl font-bold text-white mb-6">Emotional Triggers</h3>
            <div className="flex flex-wrap gap-2">
              {result.emotionalTriggers.length > 0 ? (
                result.emotionalTriggers.map((trigger, idx) => (
                  <span key={idx} className="px-4 py-2 rounded-lg text-sm font-semibold bg-red-500/10 text-red-400 border border-red-500/20">
                    {trigger}
                  </span>
                ))
              ) : (
                <span className="px-4 py-2 rounded-lg text-sm font-semibold bg-green-500/10 text-green-400 border border-green-500/20">
                  Neutral Tone
                </span>
              )}
            </div>
            <p className="text-xs text-slate-500 mt-4 leading-relaxed">
                Content designed to trigger these emotions is 4x more likely to be shared without verification.
            </p>
          </div>

          <div className="glass-panel p-6 rounded-3xl border border-primary-500/30 relative overflow-hidden">
             <div className="absolute top-0 right-0 w-32 h-32 bg-primary-500/20 rounded-full blur-[50px] -mr-10 -mt-10"></div>
            <h3 className="text-lg font-bold text-white mb-4 relative z-10">Actionable Intel</h3>
            
            <div className="space-y-3 relative z-10">
              <button className="w-full flex items-center justify-center space-x-2 py-3 rounded-xl bg-white/5 hover:bg-white/10 text-slate-300 transition-colors border border-white/5">
                 <ThumbsDown className="w-4 h-4" />
                 <span>Report as Misinformation</span>
              </button>
              <button className={`w-full flex items-center justify-center space-x-2 py-3 rounded-xl transition-all font-bold ${
                result.classification === 'Real' 
                ? 'bg-primary-600 hover:bg-primary-500 text-white shadow-lg shadow-primary-500/20' 
                : 'bg-slate-800 text-slate-500 cursor-not-allowed'
              }`}>
                 <Share2 className="w-4 h-4" />
                 <span>Verify & Share</span>
              </button>
              <button className="w-full flex items-center justify-center space-x-2 py-3 rounded-xl bg-purple-500/10 hover:bg-purple-500/20 text-purple-400 transition-colors border border-purple-500/20">
                 <Lock className="w-4 h-4" />
                 <span>Generate Blocklist Rule</span>
              </button>
            </div>
          </div>
        </div>

      </div>
    </div>
  );
};
